name: Build Terraform Deployment Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  CI_DOCKERHUB_USERNAME: ${{ secrets.CI_DOCKERHUB_USERNAME }}
  CI_DOCKERHUB_PASSWORD: ${{ secrets.CI_DOCKERHUB_PASSWORD }}
  TERRAFORM_VERSION: 1.3.9
  IMAGE_NAME: "terraform-deployment"
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Get Docker Metadata
        if: ${{ github.event_name != 'pull_request' }}
        id: terraform
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.CI_DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.CI_DOCKERHUB_USERNAME }}
          password: ${{ env.CI_DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ steps.terraform.outputs.tags }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          cache-from: type=registry,ref=${{ env.CI_DOCKERHUB_USERNAME }}/build-cache:${{ env.IMAGE_NAME }}
          cache-to: type=registry,mode=max,compression=zstd,compression-level=20,ref=${{ env.CI_DOCKERHUB_USERNAME }}/build-cache:${{ env.IMAGE_NAME }}
          build-args: |
            --build-arg TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
